# Generated by Django 4.1.4 on 2023-01-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='rating',
            field=models.CharField(blank=True, choices=[('3', '3'), ('5', '5'), ('1', '1'), ('4', '4'), ('2', '2')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('stolen', 'Stolen'), ('on_the_way', 'On The Way'), ('delivered', 'Delivered'), ('pending', 'Pending'), ('paid', 'Paid')], max_length=20),
        ),
    ]
